### ISSUE TITLE
Load trajectory in Blender

### ISSUE THREAD

**Issue by AndrewRadev** [AndrewRadev/protein-runway#11]
After https://github.com/AndrewRadev/protein-runway/issues/10

Once we have a PDB rendered, load a `.xtc` file with frames and add animations like in the create water script.

**Comment by mkrunic** [comment]
MDAnalysis can't be imported anymore, consider packaging through wheels

https://pip.pypa.io/en/stable/cli/pip_wheel/
https://github.com/pypa/cibuildwheel

**Comment by AndrewRadev** [comment]
Implemented in #36
