### ISSUE TITLE
Skeleton for the blender UI

### ISSUE THREAD

**Issue by AndrewRadev** [AndrewRadev/protein-runway#13]
- Menu documentation, although it doesn't explain things in detail: <https://docs.blender.org/api/current/bpy.types.Menu.html#submenus>. The `create_water` script adds a menu item that runs an operator: <https://github.com/AndrewRadev/protein-runway/blob/f4e60bfdc62b17dff93f223cacc4342385284124/blender/create_water.py#L145>
- Installing python modules (for biopython, mdanalysis) in blender: <https://stackoverflow.com/questions/11161901/how-to-install-python-modules-in-blender>
- Atomic blender add-on source code: <https://projects.blender.org/extensions/io_mesh_atomic>, it's a git repo that can be cloned. The `pdb_gui.py` file has the import menu: <https://projects.blender.org/extensions/io_mesh_atomic/src/branch/main/source/pdb_gui.py>

**Comment by mkrunic** [comment]
- blender add-on tutorial: https://docs.blender.org/manual/en/latest/advanced/scripting/addon_tutorial.html
