### ISSUE TITLE
Sort through data and file types

### ISSUE THREAD

**Issue by emmarousseau** [AndrewRadev/protein-runway#22]
- [ ] Specify which files are compatible to run PCA

**Comment by AndrewRadev** [comment]
In Zenodo (<https://zenodo.org/records/4650406>), we can combine:

- Trajectory file (trajectory_snapshots_...): `1fuu_noPTM_10-20ns_100snap.trr`
- Topology file (topology_stripped): `1fuu_noPTM_complex.top`

We can combine these into a PDB with the trajectory, this is an inefficient format, but it opens easily in pymol for visualization, and we take care to clean it up into just the protein residues.
