### ISSUE TITLE
Extract code in `scripts/` into classes that the snakemake file invokes

### ISSUE THREAD

**Issue by AndrewRadev** [AndrewRadev/protein-runway#42]
Instead of having procedural code in separate files, we should organize the logic into objects, similar to the mda Universe object that allows different actions. That way, we could also build separate classes, inheriting a base one, that output trajectories in a consistent format.

The code can be placed in a `lib/` directory with tests under `tests/`.

**Comment by AndrewRadev** [comment]
A potential workflow might look like:

1. Extract script logic into an object constructed with the script's inputs and a `run` method that executes the logic and writes to the output
2. Try writing tests for the logic and split it into smaller chunks that can be tested easily
3. Look for areas that can be extracted as separate objects with a well-defined purpose, for instance:
     -  The different cases in `collect_segmentation_intermediates` could be represented by classes inheriting a common base class
     - The parsing of NMD files in `generate_nmd_traj` could produce a `NormalModes` object that has a method that generates and returns a trajectory (array of coordinates)
     - Classes that operate on the data files and allow future modifications, like the one described in https://github.com/AndrewRadev/protein-runway/issues/57

**Comment by emmarousseau** [comment]
This is the rough sketch of the structure we're going for, any suggestions welcome:
![Image](https://github.com/user-attachments/assets/c8c45ca7-044a-4b1c-a135-0ab98fda26a5)

**Comment by AndrewRadev** [comment]
Why is there a `Base` object? In terms of naming, `Base` makes no sense. You could pick a `SegmentationBase` or something like this, but a common base for all possible object is unnecessary. The fact that two different objects have a trajectory doesn't require them to have a common base class, they should have a common parent if their *purpose* is the same.

To be honest, I don't understand these objects at all. Why do you have a `PDB` class, what would that contain? It doesn't look like it contains a single reference to a PDB, but multiple ones instead. So is it a collection of PDBs, is it a `ProteinStructure`? But it's not a structure, since it also has a trajectory. The `Trajectory` seems to inherit `PDB`, so it'll have both a `traj` property and a `trajectory` property? If I'm understanding it correctly, at least.

If you want to try to make this into code, by all means try it, but I think you'll end up confusing yourself and waste time. My suggestion for classes continues to be "Extract one class per script in scripts/ and then look for common structures". If you want to start with this chart and try to create something, I guess give it a shot. Maybe I'm misunderstanding something, in which case explaining it in words might help.

**Comment by AndrewRadev** [comment]
> The Trajectory seems to inherit PDB

Correction, this is not inheritance, I guess you're building one class from the output of another. But why? These different files will be used by different *parts* of the workflow. The `DCD` trajectory is used by the R script and nothing else (and is not a PDB, its presence in the `pdb/` directory is just convenience/sloppiness on my part), so there's no point in instantiating an object with all four of these values.

What *reusable* concepts are you representing with these classes? Maybe that's a better way to try to think of it. (Though, again, I don't see a point in an abstract chart when you can just try writing some code and see what sticks)

**Comment by AndrewRadev** [comment]
I'd say that this is, for now, done, thanks to #66. There's going to be some ongoing work in cleaning up and organizing the classes, and we might consider extracting the pymol generation script as well, but for now, I think we can close this.
