### ISSUE TITLE
Add more colors

### ISSUE THREAD

**Issue by AndrewRadev** [AndrewRadev/protein-runway#55]
Right now, we only have 8 colors, one of which, gray, is hard to see: https://github.com/AndrewRadev/protein-runway/blob/bbd2f7840d8e612c0c956e442e45c67eccd5e7c1/blender/extension/ui/import_pdb_operator.py/#L65-L74

We should add a much longer list, at least 10, since we generate K-means up to 10, but ideally more.

**Comment by emmarousseau** [comment]
Added 5 more colors

**Comment by AndrewRadev** [comment]
Nice 👍. Yellow and lime look a bit too similar, and so do purple and magenta, but this depends on how the domains end up oriented, not much we can do about it, I guess.
