### ISSUE TITLE
PCA on our datasets

### ISSUE THREAD

**Issue by AndrewRadev** [AndrewRadev/protein-runway#7]
Visualize trajectories over time for the existing datasets using PCA.

* for now the script works with \<noPTM PDB file\> + \<10-20ns .trr trajectory file\>

**Comment by emmarousseau** [comment]
Do we still need this done? or do we wait to run the final snakemake pipeline on the zenodo files when it's done?

**Comment by AndrewRadev** [comment]
The NMD trajectories produced by the pipeline shouldn't change anymore. The only thing that might change is clustering, but it shouldn't interfere with the existing output.

I wouldn't say we "need" it in the sense that there are more important tasks. Being able to produce a spreadsheet with how long each protein took and which ones couldn't be run (let's say on 32G memory) would be a useful report that we could summarize in the paper.

If you prefer to work on something else and leave this at a lower priority, feel free. From my perspective, you could leave a background job running with all the files and check in on it. And it would take time, so leaving it for "later" might mean it never gets done.

**Comment by AndrewRadev** [comment]
Even if we don't run it on every protein, it might be useful to pick specific ones where segmentation doesn't look ideal and try to get them to work. In one of the presentations, @evgenia-polez listed a comparison between the methods and how well they work on specific proteins. It would be useful to generate those in particular, now that we have visualization, and see how they look with convex hulls in blender.

If we can find proteins that don't look that great, I'd be interested to experiment a bit with clustering to see if there's something we can do with them. I've been mostly running 1a3w, but that one looks pretty good with chainsaw.
